Modul6/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/detail', function () {
    return view('detail');
});

Route::get('/profile', function () {
    return view('profile');
});

Route::get('/addpost', function () {
    return view('addpost');
});

Route::resource('/user', 'UserController');

Route::resource('/post', 'PostController');

Route::get('/like/{id}/{likes}', 'LikeController@like')->name('like.add');

Modul6/resources/views/addpost.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-1">
        <div class="col-md-9">
            <form method="POST" action="{{route('user.store')}}"  enctype="multipart/form-data">
                @csrf
                <h2>Add New Post</h2>
                <p>Post Caption</p>
                <input type="text" class="form-control" name="post_caption" required><br>
                <p>Post Image</p>
                <input type="file" class="form-control-file" name="post_image" required placeholder="Foto">
                <br>
                <button type="submit" class="btn btn-primary">Add New Post</button>
            </form>
        </div>
    </div>  
</div>
@endsection

Modul6/resources/views/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <img src="{{asset($detail[0]->image)}}" width="100%">
        </div>
        <div class="col-md-5">
            <a href="{{ route('user.show',$detail[0]->user_id) }}">
            <img src="{{asset($detail[0]->user->avatar)}}" width="50" style="border-radius: 50%; border: solid 1px;">
            </a> <b>{{$detail[0]->user->name}}</b> <br>
            <hr>
            <p><b>{{$detail[0]->user->email}}</b> {{$detail[0]->caption}}</p>
            <p>
                @foreach($comments as $komentar)
                <b>{{$komentar->user->email}}</b> {{$komentar->comment}} <br>
                @endforeach
            </p>
            <hr>
            <!-- <button class="like">Like</button> -->
            <a href="{{ url('like/'.$detail[0]->id.'/'.$detail[0]->likes) }}"><i class="fa fa-heart-o" style="font-size:24px; color: black;"></i></a> 
            <a href="#detail_komentar"><i class="fa far fa-comment-o" style="font-size:24px; color: black;"></i></a><br>
            <p><b>{{$detail[0]->likes}} Like</b></p>
            <form action="{{route('user.store')}}" method="POST">  
                @csrf
                <input type="hidden" name="post_id" value="{{$detail[0]->id}}">
                <div class="input-group">
                    <input type="text" class="form-control" name="comment" id="detail_komentar" required placeholder="Add a comment..">
                    <button type="submit" class="btn btn-primary" name="create_komentar" value="kirim">Send</button>
                </div>  
            </form>    
        </div>
    </div>
</div>
@endsection

Modul6/resources/views/editprofile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-1">
        <div class="col-md-9">
            <form method="POST" action="{{route('user.update', [Auth::user()->id])}}"  enctype="multipart/form-data">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="PATCH">
                <h2>Edit Profile</h2>
                <p>Title</p>
                <input type="text" class="form-control" name="profile_title" required value="{{$edit[0]->title}}"><br>
                <p>Discription</p>
                <input type="text" class="form-control" name="profile_desc" required value="{{$edit[0]->description}}"><br>
                <p>URL</p>
                <input type="text" class="form-control" name="profile_url" required value="{{$edit[0]->url}}"><br>
                <p>Profile Image</p>
                <input type="file" class="form-control-file" name="profile_image">
                <br>
                <button type="submit" class="btn btn-primary">Save Profile</button>
            </form>
        </div>
    </div>  
</div>
@endsection

Modul6/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @foreach($hasil as $isi)
        <div class="col-md-7">
            <div class="card mx-auto my-3" style="width: 100%;">
                <div class="card-header">
                    <a href="{{ route('user.show',$isi->user_id) }}">
                        <img src="{{$isi->user->avatar}}" width="50" style="border-radius: 50%; border: solid 1px;">
                    </a>
                    {{$isi->user->name}}
                </div>

                <div class="card-body">
                    <a href="{{ route('post.show', $isi->id) }}">
                        <img src="{{$isi->image}}" width="100%">
                    </a>
                </div>
                <div class="card-footer">
                    <a href="{{ url('like/'.$isi->id.'/'.$isi->likes) }}"><i class="fa fa-heart-o" style="font-size:24px; color: black;"></i></a> 
                    <a href="#home_komentar{{$isi->id}}"><i class="fa far fa-comment-o" style="font-size:24px; color: black;"></i></a><br>
                    <p><b>{{$isi->likes}} Like</b><br>
                    <b>{{$isi->user->email}}</b> {{$isi->caption}}</p>
                    @foreach($komentars as $komen)
                        @if($komen->post_id == $isi->id)
                            <b>{{$komen->email}}</b> {{$komen->comment}}<br>
                        @endif
                    @endforeach
                    <form action="{{route('user.store')}}" method="POST"> 
                        @csrf 
                        <div class="input-group">
                            <input type="hidden" name="post_id" value="{{$isi->id}}">
                            <input type="text" class="form-control" name="comment" id="home_komentar{{$isi->id}}" required placeholder="Add a comment..">
                            <button type="submit" class="btn btn-primary" name="create_komentar" value="kirim">Post</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection

Modul6/resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-md-4 text-center">
            <img src="{{asset($hasil[0]->avatar)}}" width="60%">
        </div>
        <div class="col-md-6">
            <h4>{{$hasil[0]->name}}</h4><br>
            <p>
                @if($hasil[0]->id == Auth::User()->id)
                    <a href="{{ route('user.edit', [Auth::user()->id]) }}" >Edit Profile</a><br>
                @endif
                <b>{{count($hasil[0]->posts)}}</b> Post</p>
            <p><b>{{$hasil[0]->title}}</b><br>{{$hasil[0]->description}} <br><a href="http://{{$hasil[0]->url}}" target="_blank">{{$hasil[0]->url}}</a> 
            </p>
        </div>
        <div class="col-md-2 text-right">
            @if($hasil[0]->id == Auth::User()->id)
                <a href="{{ route('user.create') }}" >Add New Post</a>
            @endif
        </div>
    </div>
    <div class="row justify-content-left my-1">
        @foreach($hasil[0]->posts as $post)
        <div class="col-md-4 my-3">
            <a href="{{ route('post.show', $post->id) }}"><img src="{{asset($post->image)}}" width="100%"></a>
        </div>
        @endforeach
    </div>
</div>
@endsection